# Generated by Django 5.1.14 on 2025-11-11 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0033_projects_soft_delete_indexes_async"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        help_text="LLM model identifier (e.g., gpt-4, claude-3-opus)",
                        max_length=128,
                    ),
                ),
                (
                    "model_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                            ("meta", "Meta"),
                        ],
                        help_text="LLM provider",
                        max_length=32,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(help_text="System prompt for the LLM evaluation"),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(
                        help_text="Encrypted API key for the LLM provider"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_tasks",
                    models.IntegerField(
                        default=0, help_text="Total number of tasks evaluated"
                    ),
                ),
                (
                    "labeled_tasks",
                    models.IntegerField(
                        default=0, help_text="Number of labeled tasks in the project"
                    ),
                ),
                (
                    "correct_labels",
                    models.IntegerField(
                        default=0,
                        help_text="Number of labels that match LLM evaluation",
                    ),
                ),
                (
                    "incorrect_labels",
                    models.IntegerField(
                        default=0,
                        help_text="Number of labels that don't match LLM evaluation",
                    ),
                ),
                (
                    "accuracy_percentage",
                    models.FloatField(
                        blank=True, help_text="Accuracy percentage of labels", null=True
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed evaluation results for each task",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if evaluation failed",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project to evaluate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "status"],
                        name="evaluations_created_e1f8e2_idx",
                    ),
                    models.Index(
                        fields=["project", "status"],
                        name="evaluations_project_698b71_idx",
                    ),
                ],
            },
        ),
    ]
